cli: Replatforming need to be able to SSH into the test environment
- Replatforming are using the `govuk-infrastructure-test` AWS account as
  a test bed for spikes into what the new platform could look like. But
  first we have to spin up an existing platform.
- Prior to this change, trying to SSH into our new jumpbox (`test` env,
  `pink` stack) meant we saw this error:

```
➜ gds govuk connect ssh -e test jumpbox
error: unknown environment 'test'

Valid environments are:
 - ci
 - integration
 - staging
 - production
```